name: quiick_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.5
  # agora_chat_sdk: 1.3.1+1
  # agora_chat_uikit: 2.0.0
  # intl: 0.19.0
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  hexcolor: ^3.0.1

  shared_preferences: 2.2.3
  sprung: ^3.0.1
  stacked: ^3.4.4
  stacked_services: ^1.6.0


  stacked_shared: ^1.4.2
  logger: any
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  faker: ^2.2.0
  audioplayers: ^6.0.0
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.1
  stacked_generator: ^1.6.1
  golden_toolkit: ^0.15.0

  logger: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/Poppins/
    - assets/fonts/Figtree/static/
    - assets/
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf


    - family: Figtree-Regular
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-Regular.ttf
    - family: Figtree-SemiBold
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-SemiBold.ttf
    - family: Figtree-Bold
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-Bold.ttf
    - family: Figtree-ExtraBold
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-ExtraBold.ttf
    - family: Figtree-Light
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-Light.ttf

